/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursoemvideo;

import java.awt.Font;

/**
 *
 * @author Administrador
 */
public class Advinhar extends javax.swing.JFrame {

    public int geniop = 0, vocep = 0;

    /**
     * Creates new form Advinhar
     */
    public Advinhar() {
        initComponents();
        mensagem.setText("<html>Vou pensar em número de <strong>1 a 5 </strong> tente adivinhar.<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        v1 = new javax.swing.JSpinner();
        botao = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        genio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        voce = new javax.swing.JLabel();
        person = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOGO DO ADIVINHO\n");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensagem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mensagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mensagem.setToolTipText("");
        mensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(mensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 70));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/conversa com balão.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/gênio.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        v1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, -1));

        botao.setText("Palpite");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });
        getContentPane().add(botao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        reset.setText("Resetar");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Gênio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        genio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genio.setText("0");
        getContentPane().add(genio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("X");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        voce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        voce.setText("0");
        getContentPane().add(voce, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        person.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        person.setText("Você");
        getContentPane().add(person, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        // TODO add your handling code here:

        int valor = (int) (1 + Math.random() * (5 - 1));
        if (valor == Integer.parseInt(v1.getValue().toString())) {
            mensagem.setFont(new Font("Arial Black", Font.PLAIN, 16));
            mensagem.setText("<html>PARABÉNS, VOCÊ ACERTOU<html>");
            vocep++;
        } else {
            mensagem.setFont(new Font("Arial", Font.PLAIN, 16));
            mensagem.setText(String.format("<html>HEHE VOCÊ ERROU, eu pensei no valor %d<html>", valor));
            geniop++;
        }
        voce.setText(Integer.toString(vocep));
        genio.setText(Integer.toString(geniop));


    }//GEN-LAST:event_botaoActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        mensagem.setFont(new Font("Arial", Font.PLAIN, 16));
        mensagem.setText("<html>Vou pensar em número de <strong>1 a 5 </strong> tente adivinhar.<html>");
        voce.setText("0");
        genio.setText("0");
        geniop = 0;
        vocep = 0;

    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Advinhar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Advinhar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Advinhar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Advinhar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Advinhar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JLabel genio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mensagem;
    private javax.swing.JLabel person;
    private javax.swing.JButton reset;
    private javax.swing.JSpinner v1;
    private javax.swing.JLabel voce;
    // End of variables declaration//GEN-END:variables
}
