/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursoemvideo;

/**
 *
 * @author Administrador
 */
public class Delta extends javax.swing.JFrame {

    /**
     * Creates new form Delta
     */
    public Delta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a = new javax.swing.JSpinner();
        b = new javax.swing.JSpinner();
        c = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        resultDelta = new javax.swing.JLabel();
        x22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        xDuasLinhas = new javax.swing.JLabel();
        xLinha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delta\n");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        a.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aStateChanged(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 75, 55, -1));

        b.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        b.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bStateChanged(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, 55, -1));

        c.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        c.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cStateChanged(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 75, 55, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("x²");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 75, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("2");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 30, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x +");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 75, 30, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("B");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 29, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("A");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("C");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 20, -1));

        a1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 0, 0));
        a1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1.setText("A");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 40, 23));

        b1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 0, 0));
        b1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1.setText("B");
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 40, 20));

        c1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 0, 0));
        c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1.setText("C");
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 130, 50, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("+");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("*");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 14, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("<html>&Delta =  </html>");
        jLabel7.setToolTipText("\n");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 35, 23));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("- 4  * ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 50, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("<html>&Delta = </html>\n");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        resultDelta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultDelta.setForeground(new java.awt.Color(0, 51, 255));
        resultDelta.setText("0");
        getContentPane().add(resultDelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        x22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        x22.setText("X'' =");
        getContentPane().add(x22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("X' =");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        xDuasLinhas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xDuasLinhas.setForeground(new java.awt.Color(0, 0, 255));
        xDuasLinhas.setText("0");
        getContentPane().add(xDuasLinhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        xLinha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xLinha.setForeground(new java.awt.Color(0, 0, 255));
        xLinha.setText("0");
        getContentPane().add(xLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("<html>Calcular &Delta </html>\n");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aStateChanged
        // TODO add your handling code here:
        a1.setText(a.getValue().toString());
    }//GEN-LAST:event_aStateChanged

    private void bStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bStateChanged
        // TODO add your handling code here:
        b1.setText(b.getValue().toString());
    }//GEN-LAST:event_bStateChanged

    private void cStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cStateChanged
        // TODO add your handling code here:
        c1.setText(c.getValue().toString());
    }//GEN-LAST:event_cStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float valor1 = Float.parseFloat(a.getValue().toString());
        float valor2 = Float.parseFloat(b.getValue().toString());
        float valor3 = Float.parseFloat(c.getValue().toString());
        float result;
        result = ((float) Math.pow(valor2, 2))-4*(valor1*valor3);
        resultDelta.setText(String.format("%.2f",result));
        float x1,x2;
        x1 = ((-1 * valor2) + (float)Math.sqrt(result)) / (2 * valor1);
        x2 = ((-1 * valor2) - (float)Math.sqrt(result)) / (2 * valor1);
        xLinha.setText(String.format("%.2f",x1));
        xDuasLinhas.setText(String.format("%.2f",x2));
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner a;
    private javax.swing.JLabel a1;
    private javax.swing.JSpinner b;
    private javax.swing.JLabel b1;
    private javax.swing.JSpinner c;
    private javax.swing.JLabel c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel resultDelta;
    private javax.swing.JLabel x22;
    private javax.swing.JLabel xDuasLinhas;
    private javax.swing.JLabel xLinha;
    // End of variables declaration//GEN-END:variables
}
